name: CI

on:
  push:
  pull_request:
  release:
    types: [released]

env:
  DOCKER_IMAGE_REGISTRY: safeglobal
  DOCKER_IMAGE_NAME: safe-client-gateway-nest
  DOCKER_BUILD_IMAGE_TAG: buildcache

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run format-check

  es-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run lint-check

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: ['test:cov', 'test:e2e:cov']
    env:
      POSTGRES_TEST_DB: test-db
      POSTGRES_TEST_USER: postgres
      POSTGRES_TEST_PASSWORD: postgres
      POSTGRES_TEST_PORT: 5433
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres:14.8
        env:
          # Should match the env above. "Variables in the env map cannot be defined in terms of other variables in the map."
          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env
          POSTGRES_DB: test-db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
      rabbitmq:
        image: rabbitmq:alpine
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl await_startup"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn run ${{matrix.task}}
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          SAFE_CONFIG_BASE_URI: ${{ secrets.SAFE_CONFIG_BASE_URI }}
          LOG_SILENT: true
      - name: Coveralls Parallel
        continue-on-error: true
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.task }}
          parallel: true

  tests-finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  docker-publish-staging:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    needs: [prettier, es-lint, tests-finish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          BUILD_NUMBER=${{ github.sha }}
          echo "BUILD_NUMBER=${BUILD_NUMBER::7}" >> "$GITHUB_ENV"
      - uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_NUMBER=${{ env.BUILD_NUMBER }}
            VERSION=${{ github.ref_name }}
          tags: ${{ env.DOCKER_IMAGE_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:staging
          # Use Registry cache backend https://docs.docker.com/build/cache/backends/registry/
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_BUILD_IMAGE_TAG }}
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_BUILD_IMAGE_TAG }},mode=max

  docker-publish-release:
    if: (github.event_name == 'release' && github.event.action == 'released')
    needs: [prettier, es-lint, tests-finish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          BUILD_NUMBER=${{ github.sha }}
          echo "BUILD_NUMBER=${BUILD_NUMBER::7}" >> "$GITHUB_ENV"
      - uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_NUMBER=${{ env.BUILD_NUMBER }}
            VERSION=${{ github.ref_name }}
          tags: |
            ${{ env.DOCKER_IMAGE_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.DOCKER_IMAGE_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          # Use Registry cache backend https://docs.docker.com/build/cache/backends/registry/
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_BUILD_IMAGE_TAG }}
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_BUILD_IMAGE_TAG }},mode=max

  autodeploy:
    runs-on: ubuntu-latest
    needs: [docker-publish-staging]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Staging
        run: bash scripts/autodeploy.sh
        env:
          AUTODEPLOY_URL: ${{ secrets.AUTODEPLOY_URL }}
          AUTODEPLOY_TOKEN: ${{ secrets.AUTODEPLOY_TOKEN }}
          TARGET_ENV: 'staging'

  generate-sdk:
    runs-on: ubuntu-latest
    # needs: [autodeploy]
    # if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn generate-sdk
      - uses: actions/checkout@v4
        with:
          repository: 5afe/cgw-sdk
          token: ${{ secrets.TEST_PERSONAL_ACCESS_TOKEN_FOR_SDK_GEN }}
          path: sdk-repo
      - run: rm -rf sdk-repo/src
      - run: mkdir -p sdk-repo/src
      - run: cp -r dist/sdk/* sdk-repo/src/
      - name: Check diffs
        working-directory: sdk-repo
        run: |
          echo git diff
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
      # If different, SDK build will fail with unclear error
      - name: Assert packageManager versions match
        run: |
          MAIN_PM_VERSION=$(jq -r '.packageManager' package.json)
          SDK_PM_VERSION=$(jq -r '.packageManager' sdk-repo/package.json)
          if [ "$MAIN_PM_VERSION" != "$SDK_PM_VERSION" ]; then
            echo "packageManager versions do not match: $MAIN_PM_VERSION (main) vs $SDK_PM_VERSION (sdk-repo)"
            exit 1
          fi
      # If same cache, lockfile will not generate correctly
      - uses: actions/cache@v3
        with:
          path: |
           ~/.yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-sdk-${{ hashFiles('sdk-repo/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-sdk-
      - name: Build SDK
        working-directory: sdk-repo
        run: |
          yarn install --immutable
          yarn build
      - name: Update package.json version
        working-directory: sdk-repo
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++;print}')
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > package_tmp.json
          mv package_tmp.json package.json
      - name: Commit and push changes
        working-directory: sdk-repo
        run: |
          git config --global user.name 'iamacook'
          git config --global user.email 'aaron@safe.global'

          git add .
          git commit -m "v$NEW_VERSION for ${{ github.sha }}"
          git push