name: Generate SDK

on:
  push:

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'yarn'
      - run: yarn install --immutable

      - name: Generate SDK
        run: yarn generate-sdk

      - name: Push to repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.TEST_PERSONAL_ACCESS_TOKEN_FOR_SDK_GEN }}
        run: |
          git config --global user.name 'iamacook'
          git config --global user.email 'aaron@safe.global'
          git clone https://github.com/5afe/cgw-sdk
          cd cgw-sdk
          if [ -d "dist" ]; then
            rm -rf dist
          fi
          mkdir -p dist
          cp -r ../dist/sdk/* dist/
          git add .
          git commit -m "Generate ${{ github.sha }} SDK"
          git push https://$PERSONAL_ACCESS_TOKEN@github.com/5afe/cgw-sdk.git
